library(ChIPseeker)
library("TxDb.Mmusculus.UCSC.mm10.knownGene")
library("org.Mm.eg.db")
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
spompe <- makeTxDbFromGFF('E:/Data/literature_data/genome/gencode.vM15.chr_patch_hapl_scaff.annotation_nochr.gtf')

cluster1 <- c('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster1.bed')
cluster2 <- c('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster2.bed')
cluster3 <- c('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster3_Repro.bed')
cluster4 <- c('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster3_Partial.bed') 
cluster5 <- c('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster3_Over.bed') 

files = list(cluster1 = cluster1 , cluster2 = cluster2 , cluster3 = cluster3 , cluster4 = cluster4 , cluster5 = cluster5)



##plotAnnoBar
peakAnnoList <- lapply(files , annotatePeak , TxDb = spompe , tssRegion=c(-1000, 1000) , overlap = "all" , addFlankGeneInfo = TRUE, flankDistance = 100000,genomicAnnotationPriority = c("Promoter", "Exon", "Intron","Intergenic"),verbose = FALSE)

pdf('F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/plot/union_peakAnno.pdf')
plotAnnoBar(peakAnnoList)
dev.off()

##Get_promoter_peaks
cluster1 <- as.data.frame(peakAnnoList[["cluster1"]]@anno)
cluster2 <- as.data.frame(peakAnnoList[["cluster2"]]@anno)
cluster3 <- as.data.frame(peakAnnoList[["cluster3"]]@anno)
cluster4 <- as.data.frame(peakAnnoList[["cluster4"]]@anno)
cluster5 <- as.data.frame(peakAnnoList[["cluster5"]]@anno)


c1 <- with(cluster1,grep("Promoter",annotation))
c1_promoter <- cluster1[c1,]
write.table(c1_promoter , "F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster_promoter_genes/union_cluster1_promoter.txt" , sep="\t" , quote=F , row.names=F)

c2 <- with(cluster2,grep("Promoter",annotation))
c2_promoter <- cluster2[c2,]
write.table(c2_promoter , "F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster_promoter_genes/union_cluster2_promoter.txt" , sep="\t" , quote=F , row.names=F)

c3 <- with(cluster3,grep("Promoter",annotation))
c3_promoter <- cluster3[c3,]
write.table(c3_promoter , "F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster_promoter_genes/union_cluster3_repro_promoter.txt" , sep="\t" , quote=F , row.names=F)

c4 <- with(cluster4,grep("Promoter",annotation))
c4_promoter <- cluster4[c4,]
write.table(c4_promoter , "F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster_promoter_genes/union_cluster3_partial_promoter.txt" , sep="\t" , quote=F , row.names=F)

c5 <- with(cluster5,grep("Promoter",annotation))
c5_promoter <- cluster5[c5,]
write.table(c5_promoter , "F:/work/ntESC_3Dreprogramming/Workspace_New/data/ATAC/ATAC_new/peaks/idr_new/classify_peaks/Cluster_promoter_genes/union_cluster3_over_promoter.txt" , sep="\t" , quote=F , row.names=F)





##cluster1


> peakAnnoList[["cluster1"]]
Annotated peaks generated by ChIPseeker
11375/11375  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
7           Promoter 89.5472527
1           1st Exon  0.1230769
5         Other Exon  1.8021978
2         1st Intron  1.4153846
6       Other Intron  1.4417582
4 Downstream (<=300)  0.5538462
3  Distal Intergenic  5.1164835


> peakAnnoList[["cluster2"]]
Annotated peaks generated by ChIPseeker
7529/7529  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
7           Promoter 12.6178775
1           1st Exon  0.6242529
5         Other Exon 10.2271218
2         1st Intron 14.1453048
6       Other Intron 28.4367114
4 Downstream (<=300)  2.3110639
3  Distal Intergenic 31.6376677


peakAnnoList[["cluster3"]]
Annotated peaks generated by ChIPseeker
11797/11797  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
7           Promoter 29.5668390
1           1st Exon  0.6527083
5         Other Exon 14.0120370
2         1st Intron  8.9853353
6       Other Intron 15.5548021
4 Downstream (<=300)  2.4582521
3  Distal Intergenic 28.7700263


> peakAnnoList[["cluster4"]]
Annotated peaks generated by ChIPseeker
672/672  peaks were annotated
Genomic Annotation Summary:
             Feature Frequency
7           Promoter 53.422619
1           1st Exon  1.785714
5         Other Exon 18.601190
2         1st Intron  3.273810
6       Other Intron  6.398810
4 Downstream (<=300)  1.636905
3  Distal Intergenic 14.880952


> peakAnnoList[["cluster5"]]
Annotated peaks generated by ChIPseeker
1527/1527  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
7           Promoter  6.8762279
1           1st Exon  0.3274394
5         Other Exon  5.1735429
2         1st Intron  9.3647675
6       Other Intron 23.7721022
4 Downstream (<=300)  2.0301244
3  Distal Intergenic 52.4557957



