library(ChIPseeker)
library("TxDb.Mmusculus.UCSC.mm10.knownGene")
library("org.Mm.eg.db")
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
files = list(cluster1 = c('/public/home/xxli/data/BDF1_New/ATAC/workspace/classify_peaks/union/union_cluster1.bed'),cluster2 = c('/public/home/xxli/data/BDF1_New/ATAC/workspace/classify_peaks/union/union_cluster2.bed'),cluster3 = c('/public/home/xxli/data/BDF1_New/ATAC/workspace/classify_peaks/union/union_cluster3.bed'))

##plotAnnoBar
peakAnnoList <- lapply(files , annotatePeak , TxDb = txdb , tssRegion=c(-1000, 1000) , overlap = "all" , addFlankGeneInfo = TRUE, flankDistance = 100000,genomicAnnotationPriority = c("Promoter", "Exon", "Intron","Intergenic"),verbose = FALSE)

pdf('union_peakAnno.pdf')
plotAnnoBar(peakAnnoList)
dev.off()

##Get_promoter_peaks
cluster1 <- as.data.frame(peakAnnoList[["cluster1"]]@anno)
cluster2 <- as.data.frame(peakAnnoList[["cluster2"]]@anno)
cluster3 <- as.data.frame(peakAnnoList[["cluster3"]]@anno)

c1 <- with(cluster1,grep("Promoter",annotation))
c1_promoter <- cluster1[c1,]
write.table(c1_promoter , "union_cluster1_promoter.txt" , sep="\t" , quote=F , row.names=F)

c2 <- with(cluster2,grep("Promoter",annotation))
c2_promoter <- cluster2[c2,]
write.table(c2_promoter , "union_cluster2_promoter.txt" , sep="\t" , quote=F , row.names=F)

c3 <- with(cluster3,grep("Promoter",annotation))
c3_promoter <- cluster3[c3,]
write.table(c3_promoter , "union_cluster3_promoter.txt" , sep="\t" , quote=F , row.names=F)

##cluster1
# Annotated peaks generated by ChIPseeker
# 15577/15577  peaks were annotated
# Genomic Annotation Summary:
             # Feature  Frequency
# 7           Promoter 71.7211273
# 1           1st Exon  2.4394941
# 5         Other Exon  3.5115876
# 2         1st Intron  3.8710920
# 6       Other Intron  5.3026899
# 4 Downstream (<=300)  0.5199974
# 3  Distal Intergenic 12.6340117


##cluster2
# Annotated peaks generated by ChIPseeker
# 13629/13629  peaks were annotated
# Genomic Annotation Summary:
             # Feature Frequency
# 7           Promoter 12.825592
# 1           1st Exon  2.619414
# 5         Other Exon  9.589845
# 2         1st Intron 14.050921
# 6       Other Intron 27.375449
# 4 Downstream (<=300)  1.511483
# 3  Distal Intergenic 32.027295

##cluster3
# Annotated peaks generated by ChIPseeker
# 26142/26142  peaks were annotated
# Genomic Annotation Summary:
             # Feature Frequency
# 7           Promoter 10.110168
# 1           1st Exon  3.255298
# 5         Other Exon 10.442965
# 2         1st Intron 11.498738
# 6       Other Intron 22.431337
# 4 Downstream (<=300)  1.407696
# 3  Distal Intergenic 40.853798


