library(DiffBind)
dbObj <- dba(sampleSheet="Samplesheet_linux.csv")
dbObj <- dba.count(dbObj, bUseSummarizeOverlaps=TRUE)
dbObj <- dba.contrast(dbObj, categories=DBA_FACTOR,minMembers = 2)
dbObj <- dba.analyze(dbObj, method=DBA_ALL_METHODS)
pdf("/public/home/lixinxin/data/BDF1/ATAC/workspace_new/peaks/idr_new/DiffBind/Cluster2_NT_fESC_diff_peaks.pdf", pointsize=10)
dba.plotPCA(dbObj,  attributes=DBA_FACTOR, label=DBA_ID)
dev.off()
comp1.deseq <- dba.report(dbObj, method=DBA_DESEQ2, contrast = 1, th=1)
comp1.edgeR <- dba.report(dbObj, method=DBA_EDGER, contrast = 1, th=1)
out <- as.data.frame(comp1.deseq)
write.table(out, file="/public/home/lixinxin/data/BDF1/ATAC/workspace_new/peaks/idr_new/DiffBind_1/Cluster2_NTs_vs_fESC_deseq2.txt", sep="\t", quote=F,row.names = NA)
out <- as.data.frame(comp1.edgeR)
write.table(out, file="/public/home/lixinxin/data/BDF1/ATAC/workspace_new/peaks/idr_new/DiffBind_1/Cluster2_NTs_vs_fESC_edgeR.txt", sep="\t", quote=F, row.names = FALSE)
